[package]
name = "black-box-planning-solver"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "black-box-planning-solver"
path = "src/main.rs"

[dependencies]
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
serde_cbor = "0.11.2"

[profile.dev]
opt-level = 2