[package]
name = "search_core"
version = "0.1.0"
edition = "2021"

[dependencies]
ordered-float = { version = "3.6", features = ["serde"] }
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
serde_cbor = "0.11.2"



